"""
Test of generate_example_gallery.py

Author: Shisato Yano
"""

from pathlib import Path
import sys

sys.path.append(str(Path(__file__).absolute().parent) + "/..")
import generate_example_gallery as gallery


def test_generate():
    # doc/EXAMPLES.md is regenerated by CI after merge, so only check the script
    # runs without error here. A broken script would otherwise surface only after merge.
    assert gallery.generate()
