"""
Test of generate_example_gallery.py

Author: Shisato Yano
"""

from pathlib import Path
import re
import sys

sys.path.append(str(Path(__file__).absolute().parent) + "/..")
import generate_example_gallery as gallery


def test_generate():
    # doc/EXAMPLES.md is regenerated by CI after merge, so only check the script
    # runs without error here. A broken script would otherwise surface only after merge.
    markdown = gallery.generate()
    assert markdown

    # Image paths are resolved from the Markdown file's directory, not the repository root
    image_paths = re.findall(r"!\[\]\((.+?)\)", markdown)
    assert image_paths
    missing = [p for p in image_paths if not (gallery.OUTPUT_PATH.parent / p).is_file()]
    assert not missing, f"Image paths not found from {gallery.OUTPUT_PATH.parent}: {missing[:3]}"
