"""
generate_example_gallery.py

Scan src/simulations, collect each algorithm's demo images (gif/png),
and generate doc/EXAMPLES.md.

Algorithms used to be added to README.md's table of contents and body by hand,
so newly added simulations were sometimes left out
(e.g. gradient_path_planning, lidar_obstacle_sensing, point_cloud_search).
This script builds the list only from the existing directories and image files,
so no simulation gets left out.

You don't need to run this script by hand. After changes are merged into main,
.github/workflows/Update_Examples_Gallery.yml runs it and commits doc/EXAMPLES.md.
To change a display name or description, edit DISPLAY_NAMES/DESCRIPTIONS below
instead of editing doc/EXAMPLES.md directly.

Author: Shisato Yano
"""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
SIMULATIONS_DIR = PROJECT_ROOT / "src" / "simulations"
OUTPUT_PATH = PROJECT_ROOT / "doc" / "EXAMPLES.md"

IMAGE_EXTENSIONS = (".gif", ".png", ".jpg")

# Display order and category names. Directories directly under src/simulations that are not listed here are skipped
CATEGORY_TITLES = {
    "localization": "Localization",
    "mapping": "Mapping",
    "path_planning": "Path Planning",
    "path_tracking": "Path Tracking",
    "perception": "Perception",
    "course": "Course",
}

# Directory name -> display name. Unlisted ones get a name generated by _default_title()
# (it looks a bit less polished, but the entry is still listed)
DISPLAY_NAMES = {
    "extended_kalman_filter_localization": "Extended Kalman Filter Localization",
    "unscented_kalman_filter_localization": "Unscented Kalman Filter Localization",
    "particle_filter_localization": "Particle Filter Localization",
    "ekf_vs_ukf_comparison": "EKF vs UKF Comparison",
    "ekf_ukf_pf_comparison": "EKF vs UKF vs Particle Filter Comparison",
    "binary_grid_map_construction": "Binary Occupancy Grid Map",
    "cost_grid_map_construction": "Cost Map",
    "potential_field_map_construction": "Potential Field Map",
    "ndt_map_construction": "NDT Map",
    "astar_path_planning": "A*",
    "astar_bidirectional_path_planning": "Bidirectional A*",
    "astar_hybrid_path_planning": "Hybrid A*",
    "dstar_path_planning": "D*",
    "dijkstra_path_planning": "Dijkstra",
    "aco_path_planning": "ACO",
    "q_learning_path_planning": "Q-Learning",
    "pso_path_planning": "PSO",
    "prm_path_planning": "PRM",
    "elastic_bands_path_planning": "Elastic Bands",
    "ga_path_planning": "GA",
    "gradient_path_planning": "Gradient Descent",
    "rrt_path_planning": "RRT",
    "rrt_star_bidirectional_path_planning": "Bidirectional RRT*",
    "rrt_star_path_planning": "RRT*",
    "informed_rrt_star_path_planning": "Informed RRT*",
    "pure_pursuit_path_tracking": "Pure pursuit Path Tracking",
    "adaptive_pure_pursuit_path_tracking": "Adaptive Pure pursuit Path Tracking",
    "rear_wheel_feedback_tracking": "Rear wheel feedback Path Tracking",
    "lqr_path_tracking": "LQR(Linear Quadratic Regulator) Path Tracking",
    "stanley_path_tracking": "Stanley steering control Path Tracking",
    "mppi_path_tracking": "MPPI Path Tracking",
    "mpc_path_tracking": "MPC Path Tracking",
    "point_cloud_rectangle_fitting": "Rectangle fitting Detection",
    "sensor_auto_calibration": "Sensor's Extrinsic Parameters Estimation",
    "lidar_obstacle_sensing": "LiDAR Obstacle Sensing",
    "point_cloud_search": "Point Cloud Nearest Neighbor Search (kd-tree)",
    "cubic_spline": "Cubic Spline Course",
}

# Short note shown under the heading (moved from the notes and credits in the old README body)
DESCRIPTIONS = {
    "aco_path_planning": "Ant Colony Optimization  \nAuthor: [Banaan Kiamanesh](https://github.com/BanaanKiamanesh)",
    "q_learning_path_planning": "Reinforcement learning with a Q-table policy",
    "pso_path_planning": "Particle Swarm Optimization",
    "dstar_path_planning": "Planning with dynamic obstacle replanning",
    "dijkstra_path_planning": "Planning (reduce frames by sampling every nth node to prevent memory exhaustion)",
    "elastic_bands_path_planning": "A* seed path smoothed with Elastic Bands optimisation",
    "ga_path_planning": "Genetic Algorithm with spline smoothing",
    "sensor_auto_calibration": "Estimation by Unscented Kalman Filter",
}


def _default_title(dir_name):
    return dir_name.replace("_", " ").title()


def _relative_to_repo_root(path):
    return path.relative_to(PROJECT_ROOT).as_posix()


def collect_gallery_entries():
    """
    Returns: {category_title: [(display_name, description, [relative image path, ...]), ...]}
    Only directories that contain both a .py file and an image file (gif/png/jpg) are included
    """
    gallery = {}

    for category_dir in sorted(SIMULATIONS_DIR.iterdir()):
        if not category_dir.is_dir():
            continue
        category_title = CATEGORY_TITLES.get(category_dir.name)
        if category_title is None:
            continue

        entries = []
        for sim_dir in sorted(category_dir.iterdir()):
            if not sim_dir.is_dir():
                continue
            if not any(p.suffix == ".py" for p in sim_dir.glob("*.py")):
                continue
            images = sorted(
                p for p in sim_dir.iterdir()
                if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
            )
            if not images:
                continue
            display_name = DISPLAY_NAMES.get(sim_dir.name, _default_title(sim_dir.name))
            description = DESCRIPTIONS.get(sim_dir.name, "")
            entries.append((display_name, description, [_relative_to_repo_root(p) for p in images]))

        if entries:
            gallery[category_title] = entries

    return gallery


def render_markdown(gallery):
    """
    Build a Markdown string from the return value of collect_gallery_entries()
    """
    lines = [
        "# Examples of Simulation",
        "",
        "This page is generated by `generate_example_gallery.py` from the demo "
        "images under `src/simulations` and updated automatically after merge. "
        "Do not edit it by hand — edit `DISPLAY_NAMES`/`DESCRIPTIONS` in the "
        "script instead.",
        "",
    ]

    for category_title in CATEGORY_TITLES.values():
        entries = gallery.get(category_title)
        if not entries:
            continue
        lines.append(f"## {category_title}")
        lines.append("")
        for display_name, description, image_paths in entries:
            lines.append(f"### {display_name}")
            if description:
                lines.append(description + "  ")
            for image_path in image_paths:
                lines.append(f"![]({image_path})  ")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate():
    """
    Generate and return the content of doc/EXAMPLES.md from the current state of src/simulations
    """
    return render_markdown(collect_gallery_entries())


def main():
    OUTPUT_PATH.write_text(generate(), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
