name: MacOS_CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.13' ]
    name: Python ${{ matrix.python-version }} CI
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Update bash
        run: brew install bash

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: run all unit tests
        run: bash run_test_suites.sh
